[package]
name = "day-03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "task-01"
path = "./src/task-01.rs"

[[bin]]
name = "task-02"
path = "./src/task-02.rs"
